### ISSUE TITLE
homepage h3 front style

### ISSUE THREAD

**Issue by guoxiangke** [guoxiangke/letchat#1]
ori
![image](https://cloud.githubusercontent.com/assets/1160703/23396115/fb0ecd98-fdcc-11e6-926c-6b415ad640b7.png)

bug:
![image](https://cloud.githubusercontent.com/assets/1160703/23396088/d64d3198-fdcc-11e6-8f26-d507f372cc96.png)

**Comment by guoxiangke** [comment]
是跟字体有关吗？

**Comment by GalinaGao123** [comment]
恩 他原来的网站 是用的自己的字体。 我没有把他的字体下载下来。

**Comment by GalinaGao123** [comment]
恩， 是字体原因，他用的自己设计的一套字体，我没下载下来。 你要是做中文网站的话就用不到他的字体了，哪个是英文的，要是做英文的话 你看是用他的还是 自己找一个细点儿的。 用他们的会不会有版权问题呢？
