### ISSUE TITLE
homepage input 框 手机版

### ISSUE THREAD

**Issue by guoxiangke** [guoxiangke/letchat#5]
wanted：
![image](https://cloud.githubusercontent.com/assets/1160703/23939360/3f20e08c-099b-11e7-8a13-d7fd2e56b0c1.png)

now：
![image](https://cloud.githubusercontent.com/assets/1160703/23939329/217c96c0-099b-11e7-9552-628340099726.png)

**Comment by guoxiangke** [comment]
1.边框覆盖
2.缺少灰底

**Comment by guoxiangke** [comment]
好像字体大小也有点出入

**Comment by GalinaGao123** [comment]
1 和 2 改了， 字体大小我这里看的一样的呢
